wip

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -583,12 +583,15 @@ jobs:
                     echo "publishing_registry_password=${{ steps.secrets.outputs.DOCKERHUB_PASSWORD }}" | tee -a "$GITHUB_OUTPUT"
                     # Image target for Hub
                     echo "publishing_image_name=${{ env.CONTAINER_IMAGE_NAME_HUB }}" | tee -a "$GITHUB_OUTPUT"
-                  else
+                  elif [[ "$version" == *-prem ]]; then
                     echo "publishing_registry=${{ env.CONTAINER_REGISTRY_CAMUNDA }}" | tee -a "$GITHUB_OUTPUT"
                     echo "publishing_registry_username=${{ steps.secrets.outputs.MACHINE_USR }}" | tee -a "$GITHUB_OUTPUT"
                     echo "publishing_registry_password=${{ steps.secrets.outputs.MACHINE_PWD }}" | tee -a "$GITHUB_OUTPUT"
                     # Image target for Camunda
                     echo "publishing_image_name=${{ env.CONTAINER_IMAGE_NAME_CAMUNDA }}" | tee -a "$GITHUB_OUTPUT"
+                  else
+                    echo "❌ Error: Unsupported version suffix in '$version'. Expected '-hub' or '-prem'."
+                    exit 1
                   fi
 
             - name: Login to the publishing registry
@@ -617,7 +620,6 @@ jobs:
 
             - name: Retag and push the image
               shell: bash
-              if: false # TODO: revert
               run: |
                   set -euo pipefail
 
