chore: implement retry mechanism on self-hosted jobs

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -232,6 +232,11 @@ jobs:
       - name: Checkout
         uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
 
+      - name: Crash this
+        run: |
+         echo "MADE UP ERROR"
+         exit 1
+
       - name: Install build-essentials for asdf
         run: |
          sudo apt-get update
@@ -531,6 +536,25 @@ jobs:
             docker buildx imagetools create -t "${{ env.dockerhub_target_name }}:latest" "${{ env.keycloak_image_name }}"
           fi
 
+  # Rerun failed jobs running on self-hosted runners in case of network issues or node preemption
+  rerun-failed-jobs:
+    needs:
+      - test-postgres-integ
+    if: failure() && fromJSON(github.run_attempt) < 3
+    runs-on: ubuntu-latest
+    steps:
+      - name: Retrigger job
+        uses: camunda/infra-global-github-actions/rerun-failed-run@main
+        with:
+          error-messages: |
+            lost communication with the server
+            The runner has received a shutdown signal
+          run-id: ${{ github.run_id }}
+          repository: ${{ github.repository }}
+          vault-addr: ${{ secrets.VAULT_ADDR }}
+          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
+          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
+
   notify-on-failure:
     runs-on: ubuntu-latest
     if: failure()
@@ -540,6 +564,7 @@ jobs:
       - list-keycloak-versions
       - test-postgres-integ
       - test-base-image
+      - rerun-failed-jobs
     steps:
       - name: Notify in Slack in case of failure
         id: slack-notification
