extract base image tag

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -524,10 +524,15 @@ jobs:
           docker pull "${{ env.keycloak_image_name }}"
 
       - name: Retag and push the image
+        shell: bash
         run: |
+          : # extract the base image tag to use it as base tag
+          base_image_tag=$(grep "ARG BASE_IMAGE_NAME=.*$1" keycloak-${{ matrix.keycloak_version }}/Dockerfile | awk -F'[:=]' '{print $NF}' | tr -d '"' || echo "Error: Image tag $1 not found in Dockerfile" && exit 1) && echo "$base_image_tag"
+          echo "base_image_tag=${base_image_tag}"
+
           docker buildx imagetools create -t "${{ env.keycloak_image_name }}" "${{ env.dockerhub_target_name }}:${{ matrix.keycloak_version }}"
-          docker buildx imagetools create -t "${{ env.keycloak_image_name }}" "${{ env.dockerhub_target_name }}:${{ matrix.keycloak_version }}-latest"
-          docker buildx imagetools create -t "${{ env.keycloak_image_name }}" "${{ env.dockerhub_target_name }}:${{ matrix.keycloak_version }}-${{ github.ref_name }}"
+          docker buildx imagetools create -t "${{ env.keycloak_image_name }}" "${{ env.dockerhub_target_name }}:${base_image_tag}"
+          docker buildx imagetools create -t "${{ env.keycloak_image_name }}" "${{ env.dockerhub_target_name }}:${base_image_tag}-${{ github.ref_name }}"
 
           if [ "$(python3 ./.github/scripts/utils/find_latest_keycloak.py ./)" = "${{ matrix.keycloak_version }}" ]; then
             docker buildx imagetools create -t "${{ env.keycloak_image_name }}" "${{ env.dockerhub_target_name }}:latest"
