fix

diff --git a/.github/workflows/build-images.yml b/.github/workflows/build-images.yml
--- a/.github/workflows/build-images.yml
+++ b/.github/workflows/build-images.yml
@@ -85,10 +85,10 @@ jobs:
       - name: Compute build image variables
         id: compute-build-image-name-step
         run: |
-          keycloak_full_version=$(grep "ARG BASE_IMAGE_NAME=.*$1" keycloak-${{ matrix.keycloak_version }}/Dockerfile | awk -F'[:=]' '{print $NF}' | tr -d '"' | awk -F'[:/-]' '{print $1}' || echo "Error: Image tag $1 not found in Dockerfile" && exit 1)
+          keycloak_full_version=$(grep "ARG BASE_IMAGE_NAME=.*$1" keycloak-${{ matrix.keycloak_version }}/Dockerfile | awk -F'[:=]' '{print $NF}' | tr -d '"' | awk -F'[:/-]' '{print $1}' || echo "Error: Image tag $1 not found in Dockerfile" && exit 1) && echo "$keycloak_full_version"
           echo "keycloak_full_version=${keycloak_full_version}"
 
-          aws_jdbc_wrapper="$(.github/scripts/utils/get_aws_jdbc_wrapper_version.sh "$keycloak_full_version" || echo "Error: Cannot get aws jdbc wrapper version for keycloak $keycloak_full_version" && exit 1)"
+          aws_jdbc_wrapper="$(.github/scripts/utils/get_aws_jdbc_wrapper_version.sh "$keycloak_full_version" || echo "Error: Cannot get aws jdbc wrapper version for keycloak $keycloak_full_version" && exit 1)" && echo "$aws_jdbc_wrapper"
           echo "aws_jdbc_wrapper=${aws_jdbc_wrapper}" >> "$GITHUB_ENV"
           echo "aws_jdbc_wrapper=${aws_jdbc_wrapper}"
 
@@ -507,7 +507,7 @@ jobs:
         shell: bash
         run: |
           : # extract the base image tag to use it as base tag
-          base_image_tag=$(grep "ARG BASE_IMAGE_NAME=.*$1" keycloak-${{ matrix.keycloak_version }}/Dockerfile | awk -F'[:=]' '{print $NF}' | tr -d '"' || echo "Error: Image tag $1 not found in Dockerfile" && exit 1)
+          base_image_tag=$(grep "ARG BASE_IMAGE_NAME=.*$1" keycloak-${{ matrix.keycloak_version }}/Dockerfile | awk -F'[:=]' '{print $NF}' | tr -d '"' || echo "Error: Image tag $1 not found in Dockerfile" && exit 1) && echo "$base_image_tag"
           echo "base_image_tag=${base_image_tag}"
 
           : # remove keycloak- prefix
